"""add llm_provider and local_model_id to project_settings

Revision ID: 92448d1db4fe
Revises: da394329def6
Create Date: 2026-09-25 19:15:11.394583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92448d1db4fe'
down_revision: Union[str, Sequence[str], None] = 'da394329def6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'project_settings',
        sa.Column(
            'llm_provider',
            sa.Enum('ANTHROPIC', 'LOCAL', name='llmprovidertype'),
            nullable=False,
            server_default='LOCAL',  # backfills existing rows (e.g. projects created before this column existed)
        ),
    )
    op.add_column('project_settings', sa.Column('local_model_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_settings', 'local_model_id')
    op.drop_column('project_settings', 'llm_provider')
    # ### end Alembic commands ###
