"""trust-driven orchestration: remove sampling/training strategy enums, add automation_enabled, held_out flag, new suggestion/annotation modes

Revision ID: d0357897ce1f
Revises: 92448d1db4fe
Create Date: 2026-09-25 22:29:10.252335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0357897ce1f'
down_revision: Union[str, Sequence[str], None] = '92448d1db4fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'project_settings',
        sa.Column('automation_enabled', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.drop_column('project_settings', 'sampling_strategy')
    op.drop_column('project_settings', 'batch_training_threshold')
    op.drop_column('project_settings', 'training_strategy')
    op.add_column('record', sa.Column('held_out_for_taxonomy_version_id', sa.Integer(), nullable=True))
    with op.batch_alter_table('record') as batch_op:
        batch_op.create_foreign_key(
            'fk_record_held_out_taxonomy_version',
            'taxonomy_version',
            ['held_out_for_taxonomy_version_id'],
            ['id'],
        )
    op.add_column(
        'training_run',
        sa.Column(
            'trigger',
            sa.Enum('BOOTSTRAP', 'SCHEDULED', 'TAXONOMY_INVALIDATED', 'MANUAL', name='trainingtrigger'),
            nullable=False,
            server_default='MANUAL',
        ),
    )
    op.drop_column('training_run', 'training_strategy')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_run', sa.Column('training_strategy', sa.VARCHAR(length=8), nullable=False))
    op.drop_column('training_run', 'trigger')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'record', type_='foreignkey')
    op.drop_column('record', 'held_out_for_taxonomy_version_id')
    op.add_column('project_settings', sa.Column('training_strategy', sa.VARCHAR(length=8), nullable=False))
    op.add_column('project_settings', sa.Column('batch_training_threshold', sa.INTEGER(), nullable=False))
    op.add_column('project_settings', sa.Column('sampling_strategy', sa.VARCHAR(length=11), nullable=False))
    op.drop_column('project_settings', 'automation_enabled')
    # ### end Alembic commands ###
