"""initial schema

Revision ID: da394329def6
Revises: 
Create Date: 2026-09-25 17:42:12.869140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da394329def6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('annotator_id', sa.String(), nullable=False),
    sa.Column('taxonomy_version_id', sa.Integer(), nullable=False),
    sa.Column('current_revision_id', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.Enum('SUBMITTED', 'SKIPPED', 'FLAGGED', name='annotationoutcome'), nullable=False),
    sa.Column('state', sa.Enum('VALID', 'NEEDS_REVIEW', 'REVIEWED', name='annotationstate'), nullable=False),
    sa.Column('annotation_mode', sa.Enum('AI_FIRST', 'HUMAN_FIRST', 'ON_DEMAND', name='annotationmode'), nullable=False),
    sa.Column('suggestion_id', sa.Integer(), nullable=True),
    sa.Column('saw_suggestion_before_submit', sa.Boolean(), nullable=True),
    sa.Column('revision_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['current_revision_id'], ['annotation_revision.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['record.id'], ),
    sa.ForeignKeyConstraint(['suggestion_id'], ['label_suggestion.id'], ),
    sa.ForeignKeyConstraint(['taxonomy_version_id'], ['taxonomy_version.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_id', 'annotator_id')
    )
    op.create_table('annotation_revision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('annotation_id', sa.Integer(), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.Enum('SUBMITTED', 'SKIPPED', 'FLAGGED', name='annotationoutcome'), nullable=False),
    sa.Column('taxonomy_version_id', sa.Integer(), nullable=False),
    sa.Column('annotation_mode', sa.Enum('AI_FIRST', 'HUMAN_FIRST', 'ON_DEMAND', name='annotationmode'), nullable=False),
    sa.Column('annotator_id', sa.String(), nullable=False),
    sa.Column('suggestion_id', sa.Integer(), nullable=True),
    sa.Column('saw_suggestion_before_submit', sa.Boolean(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['annotation_id'], ['annotation.id'], ),
    sa.ForeignKeyConstraint(['suggestion_id'], ['label_suggestion.id'], ),
    sa.ForeignKeyConstraint(['taxonomy_version_id'], ['taxonomy_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('classification_type', sa.Enum('BINARY', 'MULTICLASS', 'MULTILABEL', name='classificationtype'), nullable=False),
    sa.Column('data_type', sa.Enum('TEXT', name='datatype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dataset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source_filename', sa.String(), nullable=False),
    sa.Column('source_format', sa.Enum('CSV', 'TSV', 'JSON', 'JSONL', name='sourceformat'), nullable=False),
    sa.Column('column_mapping', sa.JSON(), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('imported_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('annotation_mode', sa.Enum('AI_FIRST', 'HUMAN_FIRST', 'ON_DEMAND', name='annotationmode'), nullable=False),
    sa.Column('training_strategy', sa.Enum('MANUAL', 'BATCH', 'ADAPTIVE', name='trainingstrategytype'), nullable=False),
    sa.Column('sampling_strategy', sa.Enum('RANDOM', 'BALANCED', 'UNCERTAINTY', 'SMART', name='samplingstrategytype'), nullable=False),
    sa.Column('batch_training_threshold', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('prompt_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('template_text', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('parameters_json', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('taxonomy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('existing_label_raw', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('taxonomy_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('taxonomy_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.Enum('INITIAL', 'RENAME', 'WORDING_CLARIFICATION', 'ADD_CLASS', 'MERGE_CLASSES', 'SPLIT_CLASS', 'REMOVE_CLASS', 'BOUNDARY_CHANGE', 'MAJOR_REDESIGN', name='taxonomychangetype'), nullable=True),
    sa.Column('change_description', sa.Text(), nullable=True),
    sa.Column('parent_version_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_version_id'], ['taxonomy_version.id'], ),
    sa.ForeignKeyConstraint(['taxonomy_id'], ['taxonomy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('label',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('taxonomy_version_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('include_criteria', sa.Text(), nullable=True),
    sa.Column('exclude_criteria', sa.Text(), nullable=True),
    sa.Column('examples', sa.JSON(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['taxonomy_version_id'], ['taxonomy_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('taxonomy_version_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('classifier_type', sa.String(), nullable=False),
    sa.Column('state', sa.Enum('INACTIVE', 'ACTIVE', 'INVALID_FOR_CURRENT_TAXONOMY', name='modelstate'), nullable=False),
    sa.Column('artifact_path', sa.String(), nullable=True),
    sa.Column('metrics_json', sa.JSON(), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['taxonomy_version_id'], ['taxonomy_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('annotation_revision_labels',
    sa.Column('revision_id', sa.Integer(), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['label.id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['annotation_revision.id'], ),
    sa.PrimaryKeyConstraint('revision_id', 'label_id')
    )
    op.create_table('evaluation_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('taxonomy_version_id', sa.Integer(), nullable=False),
    sa.Column('dataset_slice_description', sa.String(), nullable=True),
    sa.Column('metrics_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_version.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['taxonomy_version_id'], ['taxonomy_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('label_suggestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('taxonomy_version_id', sa.Integer(), nullable=False),
    sa.Column('prompt_version_id', sa.Integer(), nullable=True),
    sa.Column('model_version_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.Enum('IMPORTED', 'LLM', 'CLASSIFIER', name='suggestionsource'), nullable=False),
    sa.Column('scores_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_version.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['prompt_version_id'], ['prompt_version.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['record.id'], ),
    sa.ForeignKeyConstraint(['taxonomy_version_id'], ['taxonomy_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('taxonomy_version_id', sa.Integer(), nullable=False),
    sa.Column('training_strategy', sa.Enum('MANUAL', 'BATCH', 'ADAPTIVE', name='trainingstrategytype'), nullable=False),
    sa.Column('trigger_reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', name='trainingrunstatus'), nullable=False),
    sa.Column('annotation_count_snapshot', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('resulting_model_version_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['resulting_model_version_id'], ['model_version.id'], ),
    sa.ForeignKeyConstraint(['taxonomy_version_id'], ['taxonomy_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('label_suggestion_labels',
    sa.Column('suggestion_id', sa.Integer(), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['label.id'], ),
    sa.ForeignKeyConstraint(['suggestion_id'], ['label_suggestion.id'], ),
    sa.PrimaryKeyConstraint('suggestion_id', 'label_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('label_suggestion_labels')
    op.drop_table('training_run')
    op.drop_table('label_suggestion')
    op.drop_table('evaluation_run')
    op.drop_table('annotation_revision_labels')
    op.drop_table('model_version')
    op.drop_table('label')
    op.drop_table('taxonomy_version')
    op.drop_table('record')
    op.drop_table('taxonomy')
    op.drop_table('prompt_version')
    op.drop_table('project_settings')
    op.drop_table('dataset')
    op.drop_table('project')
    op.drop_table('annotation_revision')
    op.drop_table('annotation')
    # ### end Alembic commands ###
