import enum


class DataType(str, enum.Enum):
    TEXT = "text"


class ClassificationType(str, enum.Enum):
    BINARY = "binary"
    MULTICLASS = "multiclass"
    MULTILABEL = "multilabel"


class AnnotationMode(str, enum.Enum):
    AI_FIRST = "ai_first"
    HUMAN_FIRST = "human_first"
    ON_DEMAND = "on_demand"
    # Not a project-level setting like the other three — stamped onto an
    # annotation automatically when the orchestrator served the record as an
    # audit (a sampled check on an already-auto-labeled record) rather than a
    # fresh label. See app/orchestration.
    AUDIT = "audit"


class LLMProviderType(str, enum.Enum):
    ANTHROPIC = "anthropic"
    LOCAL = "local"


class TrainingTrigger(str, enum.Enum):
    """Replaces the old MANUAL/BATCH/ADAPTIVE strategy enum with the concrete
    conditions that actually cause a training run, per the orchestration
    redesign — see app/orchestration/orchestrator.py."""

    BOOTSTRAP = "bootstrap"  # first model for a taxonomy version, floor just cleared
    SCHEDULED = "scheduled"  # enough new confirmed annotations since the last run
    TAXONOMY_INVALIDATED = "taxonomy_invalidated"  # active model's taxonomy version changed
    MANUAL = "manual"  # explicit Train Now, always available


class SourceFormat(str, enum.Enum):
    CSV = "csv"
    TSV = "tsv"
    JSON = "json"
    JSONL = "jsonl"


class AnnotationOutcome(str, enum.Enum):
    SUBMITTED = "submitted"
    SKIPPED = "skipped"
    FLAGGED = "flagged"


class AnnotationState(str, enum.Enum):
    VALID = "valid"
    NEEDS_REVIEW = "needs_review"
    REVIEWED = "reviewed"


class SuggestionSource(str, enum.Enum):
    """Where a non-authoritative label suggestion came from.

    IMPORTED: present in the source dataset's existing label column at import time.
    LLM: generated by prompt-based AI labeling (milestone 2).
    CLASSIFIER: generated by a trained model (milestone 3).

    All three share one concept in the UI ("suggestion panel") and are always
    kept distinct from human-verified ground truth (Annotation/AnnotationRevision).
    """

    IMPORTED = "imported"
    LLM = "llm"
    CLASSIFIER = "classifier"
    # The orchestrator's fused, applied auto-label decision (both predictors
    # agreed and the class's trust tier permitted acting on it) — distinct
    # from the raw per-predictor LLM/CLASSIFIER suggestion rows, which are
    # kept for provenance regardless of whether they were acted on.
    AUTO_LABEL = "auto_label"


class ModelState(str, enum.Enum):
    INACTIVE = "inactive"
    ACTIVE = "active"
    INVALID_FOR_CURRENT_TAXONOMY = "invalid_for_current_taxonomy"


class TrainingRunStatus(str, enum.Enum):
    PENDING = "pending"
    RUNNING = "running"
    SUCCEEDED = "succeeded"
    FAILED = "failed"


class TaxonomyChangeType(str, enum.Enum):
    INITIAL = "initial"
    RENAME = "rename"
    WORDING_CLARIFICATION = "wording_clarification"
    ADD_CLASS = "add_class"
    MERGE_CLASSES = "merge_classes"
    SPLIT_CLASS = "split_class"
    REMOVE_CLASS = "remove_class"
    BOUNDARY_CHANGE = "boundary_change"
    MAJOR_REDESIGN = "major_redesign"
